apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainapp-deployment
  labels:
    app: brainapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brainapp
  template:
    metadata:
      labels:
        app: brainapp
    spec:
      containers:
        - name: brinappc
          image: 312669614823.dkr.ecr.us-east-1.amazonaws.com/braintasks-app:latest
          ports:
            - containerPort: 80

